# openapi2-run.yaml
swagger: '2.0'
info:
  title: Crypto News Crawler API
  description: API for asynchronously crawling crypto news and testing the service
  version: 1.0.0
schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://crypto-news-crawler-523673860006.us-central1.run.app/  # Replace with your Cloud Run service URL
paths:
  /crawl:
    get:
      summary: Crawl crypto news
      description: Asynchronously crawls the Crypto News website and returns the content in markdown format
      operationId: crawlCryptoNews
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              data:
                type: string
                description: The crawled data in markdown format
        '500':
          description: Internal server error
          schema:
            type: string
  /test:
    get:
      summary: Test the service
      description: A simple test endpoint to verify the API is running
      operationId: testService
      security:
        - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            properties:
              result:
                type: string
                example: hello
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
