name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Adjust to your default branch

env:
  PROJECT_ID: 'hallowed-ridge-447322-d1'
  REGION: 'us-central1'
  SERVICE: 'crypto-news-crawler' 
  DOCKER_IMAGE_NAME: crypto-news-crawler
  API_GATEWAY_CONFIG: "crypto-news-config-$(date +%Y%m%d-%H%M%S)"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for push events and enough for PRs

      - name: Determine changes
        id: determine-changes
        run: |
          # Get the list of changed files in this push
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          echo "$changes" > changes.log

          # Check for API spec changes
          if echo "$changes" | grep -E '(^parallax_spec.yaml)'; then
            echo "apichanged=true" >> $GITHUB_ENV
          else
            echo "apichanged=false" >> $GITHUB_ENV
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Authenticate Docker with GCR
        run: gcloud auth configure-docker

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gcloud'

      # Step 3: Generate a unique API Gateway config name
      - name: Set API Gateway Config Name
        id: set-config-name
        run: |
          echo "API_GATEWAY_CONFIG=parallax-config-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
      
      - name: Deploy API Gateway Configuration
        if: env.apichanged == 'true'
        run: |
          gcloud api-gateway api-configs create $API_GATEWAY_CONFIG \
            --api=parallax-api \
            --openapi-spec=parallax_spec.yaml \
            --project=${{ env.PROJECT_ID }} \
            --backend-auth-service-account='${{ secrets.API_GATEWAY_SA_EMAIL }}'

          gcloud api-gateway gateways update parallax-gateway \
            --api=parallax-api \
            --api-config=$API_GATEWAY_CONFIG \
            --location=us-central1 \
            --project=${{ env.PROJECT_ID }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          install: true
          driver: docker-container

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Deploy to Cloud Run
        if: steps.push.outputs.image != ''
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:main
          region: ${{ env.REGION }}
          flags: '--no-allow-unauthenticated'