name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'hallowed-ridge-447322-d1'
  REGION: 'us-central1'
  SERVICE: 'crypto-news-crawler' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gcloud'

      - name: Build Docker image for linux/amd64
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:$GITHUB_SHA .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:$GITHUB_SHA

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:$GITHUB_SHA
          region: ${{ env.REGION }}
          allow_unauthenticated: false  # Restrict public access

      - name: Remove public access from Cloud Run service
        run: |
          gcloud run services remove-iam-policy-binding ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --member="allUsers" \
            --role="roles/run.invoker"
